### ISSUE TITLE
Homepage changes/feedback

### ISSUE THREAD

**Issue by JoshHeng** [UWCS/stardust#38]
Nice work on the website! This is just personal feedback, feel free to take it or ignore it as you see fit. I can also contribute if you need help.

- [x] 1. The fade-in transition for the header seems a little slow. Perhaps it could be sped up, and/or the transition should start earlier instead of needing to wait a bit after load.

![image](https://github.com/UWCS/new-site/assets/34946235/bb96f27d-176a-4c39-b148-d383715093f5)

- [x] 2. It could be worth linking to specific pages here maybe? E.g. to the WASD website where it mentions WASD, etc.

![image](https://github.com/UWCS/new-site/assets/34946235/0ae464a9-73f7-461a-b7c2-709348e73cd1)

- [x] 3. I don't think this is grammatically correct

![image](https://github.com/UWCS/new-site/assets/34946235/c730731c-61ff-4b94-ad53-fc7735cbf401)

> Welcome to our new website, hopefully it has everything you need, but if you need access to the old site (dextre), find it at [old.uwcs.co.uk](https://old.uwcs.co.uk/)

> Welcome to our new website! Hopefully it has everything you need, but if you need access to the old site (dextre) you can find it at [old.uwcs.co.uk](https://old.uwcs.co.uk/)

- [x] 4. Imo socials, sponsors and footer links should open in a new tab. Use rel="noopener" to help with security if you do decide to do that.
![image](https://github.com/UWCS/new-site/assets/34946235/7472ad34-497e-47e5-9743-ea8ec8f9fb4b)

- [x] 5. The sponsors transition on hover could perhaps be sped up a little. QRT, the LRQA part of nettitude, accenture and tpp are also quite hard to read against the dark background. Also the fact that when you hover on QRT it first goes bright white then fades to dark is a bit strange. (Also applies to other places on the website)
![image](https://github.com/UWCS/new-site/assets/34946235/94f4d97f-a632-4687-a53f-7b84051829f9)

- [ ] 7. If you can be bothered, use alt text for all images for accessibility

- [x] 8. Having a hover state for the footer icons could be cool
![image](https://github.com/UWCS/new-site/assets/34946235/dc386ab5-ff49-4c5a-8c5f-f0c3d741afa3)

- [x] 9. Is having the dark news thing intended on light mode?
![image](https://github.com/UWCS/new-site/assets/34946235/36d8d6cf-760e-4fc4-ba8d-24ff3e8dfb18)

- [x] 10. The icon and heading for each category isn't vertically aligned on mobile
![image](https://github.com/UWCS/new-site/assets/34946235/dc47c756-9097-4816-9a97-cb99327f798e)

- [x] 11. Not sure if the left margin/padding is intentional on Our Community
![image](https://github.com/UWCS/new-site/assets/34946235/a75c358b-4714-4516-af09-aacfd56f8753)

- [x] 12. The open graph title has leading and trailing spaces for some reason
![image](https://github.com/UWCS/new-site/assets/34946235/70bf0bfc-a55e-46aa-93dc-ae87ff31798a)

- [x] 13. Not sure if we want to use that as the open graph image. If so, perhaps we could make a more high res version or replace it with some other image more suited to social media.
![image](https://github.com/UWCS/new-site/assets/34946235/0b521522-651c-477a-bacf-e3dd8dc2934d)

- [ ] 14. This is much more personal pref, but maybe this would look better if the line height was increased slightly?
![image](https://github.com/UWCS/new-site/assets/34946235/7e677cf2-aecd-4398-b3bb-84625a9f09af)

**Comment by ericthelemur** [comment]
All good points, fixed most, will put 2 & 6 on the todo sometime:
3: I set Zola to do it automatically for markdown forgetting it didn't apply to the rest of the templates (done manually now)
7: I do want to redo the footer a little tbh, it was straight copied from the progcomp site and hardly changed from that
10: Not sure why the pubilcity icon failed to load for you, works fine every time i've tested it
13: Probably, but the spacing is already quite particular around there, so i don't particularly want to play with it
