### ISSUE TITLE
When an uncached, large page is loaded, the page sometimes flashes white before loading in dark mode

### ISSUE THREAD

**Issue by JoshHeng** [UWCS/stardust#42]
As described in the title, basically you get flashes of white sometimes which is annoying.

Reproduction:
1. Go to the news page
2. Open the network inspector and disable page cache
3. Go to the events page
4. See that when the events page was loaded, the page went white temporarily. If it doesn't happen, try keep switching between the news and events pages

**Comment by adamskrz** [comment]
FART

(https://css-tricks.com/flash-of-inaccurate-color-theme-fart/)

**Comment by JoshHeng** [comment]
I think if you put some JS at the top of the page itself it would be better, not sure how it works currently and if it first has to wait to load in external css/js
