### ISSUE TITLE
Events are painful to look at on mobile 

### ISSUE THREAD

**Issue by adamskrz** [UWCS/stardust#44]
Huge margins on everything and only one column when two would fit fine

**Comment by ericthelemur** [comment]
There is an annoying zone at like 1.9 cols wide where there is an excessive margin. The fixed margins could be reduced a bit, but that isn't the main contributor here.

The only fix imo is to allow events to scale up/down say 10% to fit, but that does add a lot more complexity to it

**Comment by Mole1424** [comment]
![image](https://github.com/UWCS/stardust/assets/43819983/b4836cf6-4ad4-483f-9831-08955568ddf2)
:)
